// @ts-nocheck remove it once cards are implemented

import { LorcanitoActionCard } from "@lorcanito/engine";
export const iveGotADream: LorcanitoActionCard = {
  id: "4beafa90af785fbad98291f83fb66b1bd1d66034",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/129.webp",
  name: "I've Got a Dream",
  characteristics: ["action", "song"],
  text: "_(A character with cost 2 or more can ↷ to sing this song for free.)_\n\nReady chosen character of yours at a location. They can't quest for the rest of this turn. Gain lore equal to that location ◆.",
  type: "action",
  abilities: [],
  flavour:
    "Tor would like to quit and be a florist \nGunther does interior design",
  inkwell: true,
  color: "ruby",
  cost: 2,
  language: "EN",
  illustrator: "Cacciatore Michaela",
  number: 129,
  set: "ITI",
  rarity: "uncommon",
};

export const NnPuppies: LorcanitoActionCard = {
  id: "db53f26072ad4384e69619f6965bf8026ad2fef9",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/024.webp",
  name: "99 Puppies",
  characteristics: ["action"],
  text: "Whenever one of your characters quests this turn, gain 1 lore.",
  type: "action",
  abilities: [
    { name: "Whenever one of your characters quests this turn, gain 1 lore." },
  ],
  flavour: "“Two, four, six, and three is nine, plus two is 11 . . .” \n−Roger",
  color: "amber",
  cost: 5,
  language: "EN",
  illustrator: "Agnes Christianson",
  number: 24,
  set: "ITI",
  rarity: "uncommon",
};
export const bosssOrders: LorcanitoActionCard = {
  id: "e86b39dc571b4776673687e7a015caa2be568cb1",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/025.webp",
  name: "Boss’s Orders",
  characteristics: ["action"],
  text: "Chosen character gains **Support** this turn. _(Whenever they quest, you may add their ※ to another chosen character's ※ this turn.)_",
  type: "action",
  abilities: [
    {
      name: "Chosen character gains **Support** this turn. _(Whenever they quest, you may add their ※ to another chosen character's ※ this turn.)_",
    },
  ],
  flavour:
    "“Snoops! I know you can look harder! Find me that lore!” \n−Madame Medusa",
  inkwell: true,
  color: "amber",
  cost: 1,
  language: "EN",
  illustrator: "Zuzana Sokolova / Livio Cacciatore",
  number: 25,
  set: "ITI",
  rarity: "common",
};
export const healWhatHasBeenHurt: LorcanitoActionCard = {
  id: "65638b79676aeb0131fa7d34d4a093109fe15d5d",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/026.webp",
  name: "Heal What Has Been Hurt",
  characteristics: ["action", "song"],
  text: "_(A character with cost 3 or more can ↷ to sing this song for free.)_\n \nRemove up to 3 damage from chosen character. Draw a card.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 3 or more can ↷ to sing this song for free.)_\n \nRemove up to 3 damage from chosen character. Draw a card.",
    },
  ],
  flavour: "Let your power shine \nMake the clock reverse . . .",
  inkwell: true,
  color: "amber",
  cost: 3,
  language: "EN",
  illustrator: "Monica Catalano",
  number: 26,
  set: "ITI",
  rarity: "common",
};
export const quickPatch: LorcanitoActionCard = {
  id: "e6a7b978baa983c9dea71b28bc7abd8b678b8acf",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/027.webp",
  name: "Quick Patch",
  characteristics: ["action"],
  text: "Remove up to 3 damage from chosen location.",
  type: "action",
  abilities: [{ name: "Remove up to 3 damage from chosen location." }],
  flavour: "“Good as new! Well, almost.”",
  inkwell: true,
  color: "amber",
  cost: 1,
  language: "EN",
  illustrator: "Wouter Bruneel",
  number: 27,
  set: "ITI",
  rarity: "common",
};
export const theBareNecessities: LorcanitoActionCard = {
  id: "6ffe1ae50c5480627ca13c63710728ae4cc3953f",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/028.webp",
  name: "The Bare Necessities",
  characteristics: ["action", "song"],
  text: "_(A character with cost 2 or more can Exert.png to sing this song for free.)_\n\n\nChosen opponent reveals their hand and discards a non-character card of your choice.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 2 or more can Exert.png to sing this song for free.)_\n\n\nChosen opponent reveals their hand and discards a non-character card of your choice.",
    },
  ],
  flavour: "Forget about your worries and your strife. . . .",
  inkwell: true,
  color: "amber",
  cost: 2,
  language: "EN",
  illustrator: "Maxine Vee / David Navarro Arenas",
  number: 28,
  set: "ITI",
  rarity: "rare",
};
export const bestowAGift: LorcanitoActionCard = {
  id: "807f160388e9305f1bfc7a51ae8c323ebf22b9a1",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/060.webp",
  name: "Bestow a Gift",
  characteristics: ["action"],
  text: "Move 1 damage counter from chosen character to chosen opposing character.",
  type: "action",
  abilities: [
    {
      name: "Move 1 damage counter from chosen character to chosen opposing character.",
    },
  ],
  flavour:
    "“From magic ink I call this gift \nFly my minion, thy wings be swift!” \n–Maleficent",
  inkwell: true,
  color: "amethyst",
  cost: 1,
  language: "EN",
  illustrator: "Dylan Bonner",
  number: 60,
  set: "ITI",
  rarity: "common",
};
export const itCallsMe: LorcanitoActionCard = {
  id: "e38b144d7f7bf8cb5e89d31c40f3e58bf5c75010",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/061.webp",
  name: "It Calls Me",
  characteristics: ["action", "song"],
  text: "(A character with cost 1 or more can ↷ to sing this song for free.)\n\nDraw a card. Shuffle up to 3 cards from your opponent’s discard into your opponent’s deck.",
  type: "action",
  abilities: [
    {
      name: "(A character with cost 1 or more can ↷ to sing this song for free.)\n\nDraw a card. Shuffle up to 3 cards from your opponent’s discard into your opponent’s deck.",
    },
  ],
  flavour: "I am everything I’ve learned and more",
  inkwell: true,
  color: "amethyst",
  cost: 1,
  language: "EN",
  illustrator: "Luis Huerta",
  number: 61,
  set: "ITI",
  rarity: "uncommon",
};
export const lastDitchEffort: LorcanitoActionCard = {
  id: "8ef74318e6fb3c4d40140004b7b78e9fec88f728",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/062.webp",
  name: "Last-Ditch Effort",
  characteristics: ["action"],
  text: "Exert chosen opposing character. Then chosen character of yours gains **Challenger** +2 this turn. (They get +2 ※ while challenging.)",
  type: "action",
  abilities: [
    {
      name: "Exert chosen opposing character. Then chosen character of yours gains **Challenger** +2 this turn. (They get +2 ※ while challenging.)",
    },
  ],
  flavour: "“I got your back”",
  color: "amethyst",
  cost: 3,
  language: "EN",
  illustrator: "Ian MacDonald",
  number: 62,
  set: "ITI",
  rarity: "uncommon",
};
export const theBossIsOnARoll: LorcanitoActionCard = {
  id: "8964fc20b7b33b0beba45bde062d1351d6d28347",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/063.webp",
  name: "The Boss Is on a Roll",
  characteristics: ["action", "song"],
  text: "_(A character with cost 3 or more can ↷ to sing this song for free.)_\n\n\nLook at the top 5 cards of your deck. Put any number of them on the top or the bottom of your deck in any order. Gain 1 lore.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 3 or more can ↷ to sing this song for free.)_\n\n\nLook at the top 5 cards of your deck. Put any number of them on the top or the bottom of your deck in any order. Gain 1 lore.",
    },
  ],
  flavour: "Go ahead! Make your choice!",
  inkwell: true,
  color: "amethyst",
  cost: 3,
  language: "EN",
  illustrator: "Koni",
  number: 63,
  set: "ITI",
  rarity: "rare",
};
export const touchedMyHeart: LorcanitoActionCard = {
  id: "10908a4055490eb7ba4ae52f7b356031576fb6f6",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/094.webp",
  name: "Touched My Heart",
  characteristics: ["action", "song"],
  text: "_(A character with cost 2 or more can ↷ to sing this song for free.)_\n\n\nBanish chosen item.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 2 or more can ↷ to sing this song for free.)_\n\n\nBanish chosen item.",
    },
  ],
  flavour:
    "He’s not real smart, and yet, \nhe’s touched my little cowhide heart.",
  inkwell: true,
  color: "emerald",
  cost: 2,
  language: "EN",
  illustrator: "Hyuna Lee",
  number: 94,
  set: "ITI",
  rarity: "uncommon",
};
export const iWillFindMyWay: LorcanitoActionCard = {
  id: "636b4c8574c16d8e4d538badcdfec0e7c35c892d",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/095.webp",
  name: "I Will Find My Way",
  characteristics: ["action", "song"],
  text: "_(A character with cost 1 or more can ↷ to sing this song for free.)_\n\n\nChosen character of yours gets +2 ※ this turn. They may move to a location for free.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 1 or more can ↷ to sing this song for free.)_\n\n\nChosen character of yours gets +2 ※ this turn. They may move to a location for free.",
    },
  ],
  flavour: "I would go most anywhere \nTo feel like I belong",
  inkwell: true,
  color: "emerald",
  cost: 1,
  language: "EN",
  illustrator: "Carmine Pucci",
  number: 95,
  set: "ITI",
  rarity: "common",
};
export const strikeAGoodMatch: LorcanitoActionCard = {
  id: "fd4ef198ee4e021c60d006f131abb6d686298bd3",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/096.webp",
  name: "Strike a Good Match",
  characteristics: ["action", "song"],
  text: "_(A character with cost 2 or more can Exert.png to sing this song for free.)_\n\n\nDraw 2 cards, then choose and discard a card.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 2 or more can Exert.png to sing this song for free.)_\n\n\nDraw 2 cards, then choose and discard a card.",
    },
  ],
  flavour: "Please bring honor to us \nPlease bring honor to us all",
  inkwell: true,
  color: "emerald",
  cost: 2,
  language: "EN",
  illustrator: "Maxine Vee",
  number: 96,
  set: "ITI",
  rarity: "common",
};
export const divebomb: LorcanitoActionCard = {
  id: "9ce7bc84637ea2f106ffb1a6c1b846639b14f049",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/128.webp",
  name: "Divebomb",
  characteristics: ["action"],
  text: "Banish one of your characters with **Reckless** to banish chosen character with less ※ than that character.",
  type: "action",
  abilities: [
    {
      name: "Banish one of your characters with **Reckless** to banish chosen character with less ※ than that character.",
    },
  ],
  inkwell: true,
  color: "ruby",
  cost: 3,
  language: "EN",
  illustrator: "Lisanne Koeteeuw",
  number: 128,
  set: "ITI",
  rarity: "uncommon",
};
export const voyage: LorcanitoActionCard = {
  id: "3a55d636094f5ec44abdd047f7322ab18668dac9",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/131.webp",
  name: "Voyage",
  characteristics: ["action"],
  text: "Move up to 2 characters of yours to the same location for free.",
  type: "action",
  abilities: [
    { name: "Move up to 2 characters of yours to the same location for free." },
  ],
  flavour: "“We were voyagers! Why’d we stop?” –Moana",
  inkwell: true,
  color: "ruby",
  cost: 1,
  language: "EN",
  illustrator: "Alex Shin",
  number: 131,
  set: "ITI",
  rarity: "common",
};
export const distract: LorcanitoActionCard = {
  id: "298c7ac0be8ad331941010148d62e8f829eda504",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/159.webp",
  name: "Distract",
  characteristics: ["action"],
  text: "Chosen character gets -2 ※ this turn. Draw a card.",
  type: "action",
  abilities: [{ name: "Chosen character gets -2 ※ this turn. Draw a card." }],
  inkwell: true,
  color: "sapphire",
  cost: 2,
  language: "EN",
  illustrator: "Giuseppe de Maio",
  number: 159,
  set: "ITI",
  rarity: "common",
};
export const friendLikeMe: LorcanitoActionCard = {
  id: "073be8f1257104dc8f78e4288eb7ed1781206fc8",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/160.webp",
  name: "Friend Like Me",
  characteristics: ["action", "song"],
  text: "_(A character with cost 5 or more can exert to sing this song for free.)_\n\n\nEach player puts the top 3 cards of their deck into their inkwell facedown and exerted.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 5 or more can exert to sing this song for free.)_\n\n\nEach player puts the top 3 cards of their deck into their inkwell facedown and exerted.",
    },
  ],
  flavour: "You got some power in your corner now",
  inkwell: true,
  color: "sapphire",
  cost: 5,
  language: "EN",
  illustrator: "Emily Abeydeera",
  number: 160,
  set: "ITI",
  rarity: "rare",
};
export const repair: LorcanitoActionCard = {
  id: "d983a7af6632504faaa2a7c0f9d34bad28fb59f1",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/162.webp",
  name: "Repair",
  characteristics: ["action"],
  text: "Remove up to 3 damage from one of your locations or characters.",
  type: "action",
  abilities: [
    { name: "Remove up to 3 damage from one of your locations or characters." },
  ],
  flavour: "“I'm thinkin' about opening a shop here. What do you think?”",
  inkwell: true,
  color: "sapphire",
  cost: 2,
  language: "EN",
  illustrator: "Denny Minonne",
  number: 162,
  set: "ITI",
  rarity: "common",
};
export const andThenAlongCameZeus: LorcanitoActionCard = {
  id: "a02528e372649d65b6a4dd0a26fdd1db79a0f9be",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/195.webp",
  name: "And Then Along Came Zeus",
  characteristics: ["action", "song"],
  text: "_(A character with cost 4 or more can ↷ to sing this song for free.)_\n\nDeal 5 damage to chosen character or location.",
  type: "action",
  abilities: [
    {
      name: "_(A character with cost 4 or more can ↷ to sing this song for free.)_\n\nDeal 5 damage to chosen character or location.",
    },
  ],
  flavour:
    "He hurled his thunderbolt−He zapped \nLocked those suckers in a vault−They're trapped \nAnd on his own stopped chaos in its tracks",
  color: "steel",
  cost: 4,
  language: "EN",
  illustrator: "Isabella Ceravolo",
  number: 195,
  set: "ITI",
  rarity: "rare",
};
export const baBoom: LorcanitoActionCard = {
  id: "ae9c413ecfbe12c90c11689c2881a5704a11f932",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/196.webp",
  name: "Ba-Boom!",
  characteristics: ["action"],
  text: "Deal 2 damage to chosen character or location.",
  type: "action",
  abilities: [{ name: "Deal 2 damage to chosen character or location." }],
  flavour: "Bigger than your average boom!",
  inkwell: true,
  color: "steel",
  cost: 2,
  language: "EN",
  illustrator: "Heidi Neunhoffer",
  number: 196,
  set: "ITI",
  rarity: "common",
};
export const olympusWouldBeThatWay: LorcanitoActionCard = {
  id: "2578ed697e67fea1d65afd1fa0dd8a6ce275fa22",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/197.webp",
  name: "Olympus Would Be That Way",
  characteristics: ["action"],
  text: "Your characters get +3 ※ this turn while challenging a location.",
  type: "action",
  abilities: [
    {
      name: "Your characters get +3 ※ this turn while challenging a location.",
    },
  ],
  flavour:
    "“Now that I set you free, what is the first thing you are going to do?” \n–Hades",
  inkwell: true,
  color: "steel",
  cost: 1,
  language: "EN",
  illustrator: "Michaela Martin",
  number: 197,
  set: "ITI",
  rarity: "common",
};
export const riseOfTheTitans: LorcanitoActionCard = {
  id: "5fdc4634bcbbf1c063cfdb11becc5e76b44f48ac",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/198.webp",
  name: "Rise of the Titans",
  characteristics: ["action"],
  text: "Banish chosen location or item.",
  type: "action",
  abilities: [{ name: "Banish chosen location or item." }],
  flavour: "“Oh, we're in trouble, big trouble!” \n–Hermes",
  inkwell: true,
  color: "steel",
  cost: 3,
  language: "EN",
  illustrator: "Nicola Saviori",
  number: 198,
  set: "ITI",
  rarity: "uncommon",
};
