// @ts-nocheck remove it once cards are implemented

import { LorcanitoCard, LorcanitoLocationCard } from "@lorcanito/engine";

export const forbiddenMountainMaleficentsCastle: LorcanitoLocationCard = {
  id: "d68525b99df56fc51bc4f5acf0e6a8487dd50d42",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/066.webp",
  name: "Forbidden Mountain",
  title: "Maleficent's Castle",
  characteristics: ["location"],
  flavour: "",
  inkwell: true,
  color: "amethyst",
  cost: 2,
  willpower: 6,
  lore: 1,
  moveCost: 2,
  language: "EN",
  illustrator: "Jimmy Lo",
  number: 66,
  set: "ITI",
  rarity: "common",
};

export const neverLandMermaidLagoon: LorcanitoCard = {
  id: "a7af22b5f824cc71c66ffeb16db4962e299df487",
  type: "location",
  implemented: true,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/032.webp",
  name: "Never Land",
  title: "Mermaid Lagoon",
  characteristics: ["location"],
  flavour:
    "The mermaids told Peter they'd seen some items floating by several days earlier, but they were more concerned that one of their sisters had gone missing.",
  inkwell: true,
  color: "amber",
  cost: 1,
  moveCost: 1,
  strength: 1,
  willpower: 4,
  lore: 1,
  language: "EN",
  illustrator: "Cecile Carre",
  number: 32,
  set: "ROF",
  rarity: "common",
};
export const prideLandsPrideRock: LorcanitoCard = {
  id: "88803aae0a66b944204fbd7a10d734505bfcf3cd",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/033.webp",
  name: "Pride Lands",
  title: "Pride Rock",
  characteristics: ["location"],
  text: "**WE ARE ALL CONNECTED** Characters get +2 ⛨ while here.\n\n\n**LION HOME** If you have a Prince or King character here, you pay 1 ⬡ less to play characters.",
  abilities: [
    {
      name: "**WE ARE ALL CONNECTED** Characters get +2 ⛨ while here.\n\n\n**LION HOME** If you have a Prince or King character here, you pay 1 ⬡ less to play characters.",
    },
  ],
  color: "amber",
  cost: 2,
  strength: 2,
  willpower: 7,
  lore: 1,
  moveCost: 2,
  language: "EN",
  illustrator: "Beverly Arce / Jonathan Livslyst",
  number: 33,
  set: "ROF",
  rarity: "rare",
};
export const tianasPalaceJazzRestaurant: LorcanitoCard = {
  id: "ee2a3d0e30b3f2942f7d81769bedd2661e7435d3",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/034.webp",
  name: "Tiana's Palace",
  title: "Jazz Restaurant",
  characteristics: ["location"],
  text: "**NIGHT OUT** Characters can't be challenged while here.",
  abilities: [
    { name: "**NIGHT OUT** Characters can't be challenged while here." },
  ],
  flavour: "In New Orleans, dreams can come true.",
  color: "amber",
  cost: 3,
  strength: 2,
  willpower: 8,
  lore: 1,
  moveCost: 2,
  language: "EN",
  illustrator: "Valerio Buonfantino",
  number: 34,
  set: "ROF",
  rarity: "uncommon",
};

export const theQueensCastleMirrorChamber: LorcanitoCard = {
  id: "4d386c2d8ad5dde814ab61a714a1324ac97b04a9",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/067.webp",
  name: "The Queen's Castle",
  title: "Mirror Chamber",
  characteristics: ["location"],
  text: "**USING THE MIRROR** At the start of your turn, for each character you have here, you may draw a card.",
  abilities: [
    {
      name: "**USING THE MIRROR** At the start of your turn, for each character you have here, you may draw a card.",
    },
  ],
  flavour:
    "Those who visit the mirror can choose their question−but not the answer.",
  inkwell: true,
  color: "amethyst",
  cost: 4,
  strength: 1,
  willpower: 7,
  lore: 2,
  moveCost: 1,
  language: "EN",
  illustrator: "Matthew Oates",
  number: 67,
  set: "ROF",
  rarity: "rare",
};
export const theSorcerersTowerWondrousWorkspace: LorcanitoCard = {
  id: "834fccce3c2d038fd5cf66df755b7d4d189b407d",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/068.webp",
  name: "The Sorcerer's Tower",
  title: "Wondrous Workspace",
  characteristics: ["location"],
  text: "**BROOM CLOSET** Your characters named Magic Broom may move here for free.\n\n\n**MAGICAL POWER** Characters get +1 ◆ while here.",
  abilities: [
    {
      name: "**BROOM CLOSET** Your characters named Magic Broom may move here for free.\n\n\n**MAGICAL POWER** Characters get +1 ◆ while here.",
    },
  ],
  flavour: "Everything you need to make some magic.",
  inkwell: true,
  color: "amethyst",
  cost: 3,
  strength: 2,
  willpower: 7,
  lore: 0,
  moveCost: 2,
  language: "EN",
  illustrator: "Wietse Treurniet",
  number: 68,
  set: "ROF",
  rarity: "uncommon",
};

export const deVilManorCruellasEstate: LorcanitoCard = {
  id: "ab0224fee1287c1031406c2e0e0907b059b5dac7",
  type: "location",
  implemented: true,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/100.webp",
  name: "De Vil Manor",
  title: "Cruella's Estate",
  characteristics: ["location"],
  flavour:
    "“They say the ol' place is haunted, or bewitched, or some such fiddle-faddle.”\n–Colonel",
  inkwell: true,
  color: "emerald",
  cost: 1,
  strength: 1,
  willpower: 4,
  lore: 1,
  moveCost: 1,
  language: "EN",
  illustrator: "Ryan Moeck",
  number: 100,
  set: "ROF",
  rarity: "common",
};
export const fangRiverCity: LorcanitoCard = {
  id: "b277697dc2530c0b34967261567ca4ba0db831f4",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/101.webp",
  name: "Fang",
  title: "River City",
  characteristics: ["location"],
  text: "**SURROUNDED BY WATER** Characters gain **Ward** and **Evasive** while here. _(Opponents can't choose them except to challenge. Only characters with Evasive can challenge them.)_",
  abilities: [
    {
      name: "**SURROUNDED BY WATER** Characters gain **Ward** and **Evasive** while here. _(Opponents can't choose them except to challenge. Only characters with Evasive can challenge them.)_",
    },
  ],
  flavour:
    "A nation protected by fierce assassins and their even fiercer cats.",
  inkwell: true,
  color: "emerald",
  cost: 4,
  strength: 2,
  willpower: 6,
  lore: 2,
  moveCost: 2,
  language: "EN",
  illustrator: "Michael Guimont",
  number: 101,
  set: "ROF",
  rarity: "rare",
};
export const kuzcosPalaceHomeOfTheEmperor: LorcanitoCard = {
  id: "603afc4f7beab157a94198f951a610f5d428ee37",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/102.webp",
  name: "Kuzco's Palace",
  title: "Home of the Emperor",
  characteristics: ["location"],
  text: "**CITY WALLS** Whenever a character is challenged and banished while here, banish the challenging character.",
  abilities: [
    {
      name: "**CITY WALLS** Whenever a character is challenged and banished while here, banish the challenging character.",
    },
  ],
  flavour:
    "“Sure it's a little small, but also it DOESN'T HAVE A POOL!” −Kuzco",
  inkwell: true,
  color: "emerald",
  cost: 3,
  strength: 3,
  willpower: 7,
  lore: 1,
  moveCost: 3,
  language: "EN",
  illustrator: "Andreas Rocha",
  number: 102,
  set: "ROF",
  rarity: "uncommon",
};

export const agrabahMarketplace: LorcanitoCard = {
  id: "5d933abcc11104bfd7c43d8419896778dd0f96cc",
  type: "location",
  implemented: true,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/134.webp",
  name: "Agrabah",
  title: "Marketplace",
  characteristics: ["location"],
  flavour:
    "“Welcome to Agrabah, city of mystery, of enchantment, and the finest merchandise this side of the river.” \n–Merchant",
  inkwell: true,
  color: "ruby",
  cost: 3,
  strength: 1,
  willpower: 5,
  moveCost: 1,
  lore: 2,
  language: "EN",
  illustrator: "Kaitlin Cuthbertson",
  number: 134,
  set: "ROF",
  rarity: "common",
};
export const jollyRogerHooksShip: LorcanitoCard = {
  id: "767a352cea17e219c9d04d894746dd1b6c8391a5",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/135.webp",
  name: "Jolly Roger",
  title: "Hook's Ship",
  characteristics: ["location"],
  text: "**LOOK ALIVE, YOU SWABS!** Characters gain **Rush** while here. _(They can challenge the turn they're played.)_\n\n\n**ALL HANDS ON DECK!** Your Pirate characters may move here for free.",
  abilities: [
    {
      name: "**LOOK ALIVE, YOU SWABS!** Characters gain **Rush** while here. _(They can challenge the turn they're played.)_\n\n\n**ALL HANDS ON DECK!** Your Pirate characters may move here for free.",
    },
  ],
  color: "ruby",
  cost: 1,
  strength: 2,
  willpower: 5,
  lore: 0,
  moveCost: 2,
  language: "EN",
  illustrator: "Nicolas Ky",
  number: 135,
  set: "ROF",
  rarity: "uncommon",
};
export const rlsLegacySolarGalleon: LorcanitoCard = {
  id: "995c9f0e0cf38143cd284765b340ad091d6400d7",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/136.webp",
  name: "RLS Legacy",
  title: "Solar Galleon",
  characteristics: ["location"],
  text: "**THIS IS OUR SHIP** Characters gain **Evasive** while here. _(Only characters with Evasive can challenge them.)_\n\n\n**HEAVE TOGETHER NOW** If you have a character here, you pay 2 ⬡ less to move a character of yours here.",
  abilities: [
    {
      name: "**THIS IS OUR SHIP** Characters gain **Evasive** while here. _(Only characters with Evasive can challenge them.)_\n\n\n**HEAVE TOGETHER NOW** If you have a character here, you pay 2 ⬡ less to move a character of yours here.",
    },
  ],
  color: "ruby",
  cost: 4,
  strength: 3,
  willpower: 8,
  moveCost: 3,
  lore: 2,
  language: "EN",
  illustrator: "Wietse Treurniet",
  number: 136,
  set: "ROF",
  rarity: "rare",
};
export const bellesHouseMauricesWorkshop: LorcanitoCard = {
  id: "3bcfd0b06e7e6247b16882d356b1b76128effb30",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/168.webp",
  name: "Belle's House",
  title: "Maurice's Workshop",
  characteristics: ["location"],
  text: "**LABORATORY** If you have a character here, you pay 1 ⬡ less to play items.",
  abilities: [
    {
      name: "**LABORATORY** If you have a character here, you pay 1 ⬡ less to play items.",
    },
  ],
  flavour: "Some of the most important tools in Lorcana are crafted here.",
  inkwell: true,
  color: "sapphire",
  cost: 1,
  strength: 2,
  willpower: 6,
  lore: 0,
  moveCost: 2,
  language: "EN",
  illustrator: "Alex Shin",
  number: 168,
  set: "ROF",
  rarity: "rare",
};
export const motunuiIslandParadise: LorcanitoCard = {
  id: "aa21e8260cdea0f96c0cf60bc670ea1e3cf34453",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/170.webp",
  name: "Motunui",
  title: "Island Paradise",
  characteristics: ["location"],
  text: "**REINCARNATION** Whenever a character is banished while here, you may put that card into your inkwell facedown and exerted.",
  abilities: [
    {
      name: "**REINCARNATION** Whenever a character is banished while here, you may put that card into your inkwell facedown and exerted.",
    },
  ],
  inkwell: true,
  color: "sapphire",
  cost: 2,
  strength: 1,
  willpower: 5,
  lore: 1,
  moveCost: 1,
  language: "EN",
  illustrator: "Etienne Savoie",
  number: 170,
  set: "ROF",
  rarity: "uncommon",
};

export const mauisPlaceOfExileHiddenIsland: LorcanitoCard = {
  id: "d871759d48077572202b219c0f8ce2488a004d24",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/202.webp",
  name: "Maui's Place of Exile",
  title: "Hidden Island",
  characteristics: ["location"],
  text: "**ISOLATED** Characters gain **Resist** +1 while here. _(Damage dealt to them is reduced by 1.)_",
  abilities: [
    {
      name: "**ISOLATED** Characters gain **Resist** +1 while here. _(Damage dealt to them is reduced by 1.)_",
    },
  ],
  flavour: "Nothing but boulders and sand-easy to miss.",
  inkwell: true,
  color: "steel",
  cost: 2,
  strength: 1,
  willpower: 5,
  lore: 0,
  moveCost: 1,
  language: "EN",
  illustrator: "Jeremy Adams",
  number: 202,
  set: "ROF",
  rarity: "rare",
};
export const nottinghamPrinceJohnsCastle: LorcanitoCard = {
  id: "9caf373ada45090ed37e08684e7850dcc5135916",
  type: "location",
  implemented: true,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/203.webp",
  name: "Nottingham",
  title: "Prince John's Castle",
  characteristics: ["location"],
  flavour:
    "Sir Hiss: “I say, ssssire, your mother’s castle would be the perfect place to bring our plan to life!” \nPrince John: “Mummy!”",
  inkwell: true,
  color: "steel",
  cost: 2,
  strength: 1,
  willpower: 6,
  lore: 1,
  moveCost: 1,
  language: "EN",
  illustrator: "Bryn Jones",
  number: 203,
  set: "ROF",
  rarity: "common",
};
export const theBayouMysteriousSwamp: LorcanitoCard = {
  id: "58d43d41e83bd57d1cc875f408605c0a4f4090dc",
  type: "location",
  implemented: false,
  url: "https://lorcanito.imgix.net/images/cards/EN/003/204.webp",
  name: "The Bayou",
  title: "Mysterious Swamp",
  characteristics: ["location"],
  text: "**SHOW ME THE WAY** Whenever a character quests while here, you may draw a card, then choose and discard a card.",
  abilities: [
    {
      name: "**SHOW ME THE WAY** Whenever a character quests while here, you may draw a card, then choose and discard a card.",
    },
  ],
  flavour: "A place to find what you need, not just what you want.",
  inkwell: true,
  color: "steel",
  cost: 1,
  strength: 1,
  willpower: 3,
  lore: 1,
  moveCost: 1,
  language: "EN",
  illustrator: "Ryan Moeck",
  number: 204,
  set: "ROF",
  rarity: "uncommon",
};
